# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: echo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='echo.proto',
  package='proto',
  syntax='proto3',
  serialized_options=b'Z\033echo_bachelor_example/proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\necho.proto\x12\x05proto\"\x1f\n\x0c\x65\x63ho_message\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t28\n\x04\x45\x63ho\x12\x30\n\x04Send\x12\x13.proto.echo_message\x1a\x13.proto.echo_messageB\x1dZ\x1b\x65\x63ho_bachelor_example/protob\x06proto3'
)




_ECHO_MESSAGE = _descriptor.Descriptor(
  name='echo_message',
  full_name='proto.echo_message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='content', full_name='proto.echo_message.content', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=52,
)

DESCRIPTOR.message_types_by_name['echo_message'] = _ECHO_MESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

echo_message = _reflection.GeneratedProtocolMessageType('echo_message', (_message.Message,), {
  'DESCRIPTOR' : _ECHO_MESSAGE,
  '__module__' : 'echo_pb2'
  # @@protoc_insertion_point(class_scope:proto.echo_message)
  })
_sym_db.RegisterMessage(echo_message)


DESCRIPTOR._options = None

_ECHO = _descriptor.ServiceDescriptor(
  name='Echo',
  full_name='proto.Echo',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=54,
  serialized_end=110,
  methods=[
  _descriptor.MethodDescriptor(
    name='Send',
    full_name='proto.Echo.Send',
    index=0,
    containing_service=None,
    input_type=_ECHO_MESSAGE,
    output_type=_ECHO_MESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ECHO)

DESCRIPTOR.services_by_name['Echo'] = _ECHO

# @@protoc_insertion_point(module_scope)
